layout_spectrum: 0.7157472816761583
typography_spectrum: 0.02830684627406299
color:
  brandStrength: 0.5370352671016008
  lightness: 0.7142398310825229
  saturation: 0.7759108832105994
  rhythmicContrast: 0.8433995090890676
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
name: Potentia
title: >-
  Potentia is an applied research, open source think tank. The mission is to
  democratize research, and solve the world’s most nagging and devastating
  problems, by open collaboration between academic researchers and social and
  political policy decision makers, but more importantly, and uniquely, we plan
  to solve our world’s problems through open collaboration with the public. We
  are rethinking the model of traditional think tanks, which are populated by a
  decidedly exclusive group of elite researchers, yet highly influential in
  policies that affect the masses. We will open up the discussion by bringing
  together academic researchers with the public to discuss, research and design
  solutions to our world’s most overwhelming social issues; and then work with
  political, business, and social leaders to disseminate and implement research
  findings.
